### ISSUE TITLE
[Staking App] Profile Pictures for delates are missing

### ISSUE THREAD

**Issue by dimsome** [mstable/mStable-apps#156]
**Describe the bug**
Profile pictures for delegates are missing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://staking.mstable.app/#/vote
2. See missing profile picture
3. Also in View Leaderboard and when selecting a single delegate

**Expected behaviour**
Picture should appear

**Screenshots**

![Screen Shot 2022-05-20 at 13 09 08](https://user-images.githubusercontent.com/69167058/169463889-59cfa102-53d3-4e53-b170-444c8ad11453.png)

**Comment by toniocodo** [comment]
I have updated img src path to point to `https://gateway.pinata.cloud/ipfs/` but still have errors while loading the images. After having accessed them directly or waited long enough, they finally appear. 

![image](https://user-images.githubusercontent.com/13216617/169589194-27b126d5-1a0c-4577-9a7c-ef4b0ff75e48.png)

imo, this is mostly due to ipfs file serve being too slow, probably worth to check the pinata configuration/perfs
